create table contacts (
    id bigint generated by default as identity primary key,
    phone_number varchar(16),
    email varchar(320),
    nsu_email varchar(320),
    additional_info text
);

create table organization (
    id int generated by default as identity primary key,
    name varchar(256) not null
);

create table organizational_unit (
    id bigint generated by default as identity primary key,
    name varchar(128) not null,
    contacts_id bigint unique references contacts(id) on delete set null,
    organization_id integer references organization(id) on delete set null
);

create table employee (
    id uuid primary key,
    last_name varchar(64) not null,
    first_name varchar(64) not null,
    middle_name varchar(64),
    agreement boolean not null,
    has_completed_advanced_courses boolean not null,
    needs_mandatory_election boolean not null,
    has_a_higher_education boolean not null,
    snils varchar(16) unique,
    inn varchar(16) unique,
    is_archived boolean not null,
    contacts_id bigint unique references contacts(id) on delete set null
);

create table employment_status (
    id int generated by default as identity primary key,
    is_employeed_in_nsu boolean not null,
    employment_info text,
    employee_id uuid unique not null references employee(id) on delete cascade
);

create table employment_record (
    id int generated by default as identity primary key,
    date_of_receipt date not null,
    employee_id uuid unique not null references employee(id) on delete cascade
);

create table passport_info (
    id int generated by default as identity primary key,
    passport_info text,
    employee_id uuid unique not null references employee(id) on delete cascade
);

create table academic_degree (
    id int generated by default as identity primary key,
    name varchar(128) not null,
    employee_id uuid unique not null references employee(id) on delete cascade
);

create table work_experience (
    id int generated by default as identity primary key,
    days int not null,
    employee_id uuid unique not null references employee(id) on delete cascade
);

create table certificate_of_no_criminal_record (
    id int generated by default as identity primary key,
    date_of_receipt date not null,
    active_until date not null,
    employee_id uuid unique not null references employee(id) on delete cascade
);

create table post (
    id int generated by default as identity primary key,
    name varchar(256) not null
);

create table employment_type (
    id int generated by default as identity primary key,
    name varchar(256) not null
);

create table employee_employment (
    employee_id uuid not null references employee(id) on delete cascade,
    post_id int references post(id) on delete cascade,
    employment_type_id int references employment_type(id) on delete cascade,
    primary key(employee_id, post_id, employment_type_id)
);
