spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 539777559204-07npafenqtct9sqgvbc9f2ba1p7d7d72.apps.googleusercontent.com
            client-secret: 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
            scope: email, profile, https://www.googleapis.com/auth/gmail.send, https://www.googleapis.com/auth/gmail.compose
            redirect-uri: http://localhost:8080/login/oauth2/code/google

        provider:
          google:
            user-info-uri: https://openidconnect.googleapis.com/v1/userinfo

  application:
    name: department-assistant
    version: 0.0.1-SNAPSHOT
  datasource:
    url: ${DEPARTMENT_DB_URI:jdbc:postgresql://localhost:5432/department-db}
    username: ${DEPARTMENT_DB_USERNAME:assistant-back}
    password: ${DEPARTMENT_DB_PASSWORD:ZnVjayB5ZWFoIQ==}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8080

file:
  storage-path: ./storage


