spring:
  application:
    name: department-assistant
    version: 0.0.1-SNAPSHOT
  datasource:
    url: ${DEPARTMENT_DB_URI:jdbc:postgresql://localhost:5432/department-db}
    username: ${DEPARTMENT_DB_USERNAME:assistant-back}
    password: ${DEPARTMENT_DB_PASSWORD:ZnVjayB5ZWFoIQ==}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080
